## 1
name: Tests (Unit)

## Actions that will be executed when you push code currently none
on:
  pull_request:
    branches:
      - 'master'

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Unit tests
        run: ./gradlew test